#!/usr/bin/python
import os
import sqlalchemy as sqla
import sqlalchemy.orm as sqlo
import csv
import hashlib
import string
import random

def generate_password():
    list = string.ascii_letters + string.digits
    return ''.join(random.choice(list) for i in range(16))

def main():
    engine = sqla.create_engine("postgres:///portal")
    db = sqlo.scoped_session(sqlo.sessionmaker(bind=engine))

    with open("schools.csv") as csv_file:
        reader = csv.reader(csv_file, delimiter=',')
        f = open("logs", "w")
        for abbrev, name in reader:
            password = generate_password()
            passwd = hashlib.sha512(password.encode('utf-8')).hexdigest()
            db.execute("INSERT INTO schools (abbrev, name, passwd) VALUES(:abbrev, :name, :passwd)", {"abbrev": abbrev, "name": name, "passwd":passwd})
            f.write(f"Added new Entry: Abbrev: %5s | Name: %35s | Password; %s \n" % (abbrev, name, password))

    db.commit()

if __name__ == "__main__":
    main()
