#!/usr/bin/python
import os
import sqlalchemy as sqla
import sqlalchemy.orm as sqlo
import csv
import hashlib
import string
import random

def generate_password():
    list = string.ascii_letters + string.digits
    return ''.join(random.choice(list) for i in range(16))

def main():
    engine = sqla.create_engine("postgres:///portal")
    db = sqlo.scoped_session(sqlo.sessionmaker(bind=engine))

    with open("venues.csv") as csv_file:
        reader = csv.reader(csv_file, delimiter=',')
        f = open("venues_logs", "w")
        count = 0
        for name, place in reader:
            count += 1
            if count == 1:
                continue
            db.execute("INSERT INTO venues (name, place) VALUES(:name, :place)", {"name": name, "place":place})
            f.write(f"Added new Entry: Name: %5s | Place %s \n" % (name, place))

    db.commit()

if __name__ == "__main__":
    main()
